#!/usr/bin/env bash

error() {
	echo -n "ERROR: "
	for msg in "$@"; do echo -e "$msg"; done
	exit 1
}

jarvis-dir() {
	local dir=$(pwd)
	cd -P .
	while [ ! -d '.jarvis' ]; do
		cd ..
		[ $(pwd) != '/' ] ||
			error 'JARVIS has not been initialized.' \
				'You can initialize JARVIS by running "'$0' init".'
	done &&
	echo $(pwd)'/.jarvis'
	cd $dir
}

tasks-dir() {
	echo $(jarvis-dir)/tasks
}

init() {
	[ -e '.jarvis' ] &&
	error 'Initialization failed.' '".jarvis" already exists.'
	mkdir -p .jarvis/tasks
}

which-task() {
	[ $1 ] || error 'Please specify a task.' 'Usage: '$0' which <task>'
	local task=$(tasks-dir)/$1
	[ -x "$task" ] ||
		error 'JARVIS does not know how to "'$1'".'
	echo $task
}

perform() {
	while getopts :I: opt; do
		case $opt in
		I) local id=$OPTARG ;;
		\?) error 'Illegal option: -'$OPTARG \
				'Usage: '$0' [-I <id>] <task> [arguments]...' ;;
		esac
	done
	shift $((OPTIND-1))
	local task=$1
	shift
	$(which-task $task) $@
}

case "$1" in
'') error 'No task to do.' \
		'Usage: '$0' (init | which | <task>) [arguments]...' ;;
init) init ;;
which) which-task $2 ;;
*) perform $@ ;;
esac
