#!/usr/bin/env bash

error() {
	echo -n "ERROR: "
	for msg in "$@"; do echo -e "$msg"; done
	exit 1
}

jarvis-dir() {
	dir=$(pwd)
	cd -P .
	while [ ! -d '.jarvis' ]; do
		cd ..
		[ $(pwd) != '/' ] ||
			error 'JARVIS has not been initialized.' \
				'You can initialize JARVIS by running "'$0' init".'
	done &&
	echo $(pwd)'/.jarvis'
	cd $dir
}

tasks-dir() {
	echo $(jarvis-dir)/tasks
}

init() {
	[ -e '.jarvis' ] &&
	error 'Initialization failed.' '".jarvis" already exists.'
	mkdir -p .jarvis/tasks
}

perform() {
	task=$(tasks-dir)/$1
	[ -x "$task" ] ||
		error 'JARVIS does not know how to "'$1'".'
	shift
	$task $@
}

case "$1" in
'') error 'No task to do.' \
		'Usage: '$0' (init | <task>) [arguments]...' ;;
init) init ;;
*) perform $@ ;;
esac
